#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

unsetopt PROMPT_SP

# Default programs:
export EDITOR="vimd"
export TERMINAL="footie"
export BROWSER="firefox"
export MANPAGER="less -R --use-color -Dd+m -Du+c"

# XDG stuff
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CURRENT_DESKTOP=sway

# ~/ Clean-up:
export HISTFILE="$XDG_DATA_HOME/history"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GOPATH="$XDG_DATA_HOME/go"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export ANDROID_USER_HOME="$XDG_DATA_HOME/android" 
export ANDROID_HOME=/opt/android-sdk/Sdk
export ANDROID_AVD_HOME="$XDG_DATA_HOME/android/avd"
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

# Program settings
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/.zcompdump-$HOST"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/.password-store"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export SUDO_ASKPASS="/usr/bin/pinentry-bemenu"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export _JAVA_AWT_WM_NONREPARENTING=1 #fix Java apps (like android studio)
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
source "$XDG_CONFIG_HOME/fzf/fzfrc" # fzf settings
export LESS='-R --use-color -Dd+m$Du+c' # coloring less
export REFER="./biba" # for groff
export QT_STYLE_OVERRIDE=adwaita # QT style
source "$XDG_CONFIG_HOME/bemenu/bemenurc" # bemenu setting

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1

# Wayland related settings / HiDpi related settings
export MOZ_ENABLE_WAYLAND=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1.5
export QT_SCALE_FACTOR=1.5
export GDK_DPI_SCALE=1.5
export GDK_SCALE=2
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.

# Colors
export PRIMARY_COLOR="B400B4"
export PREFERRED_GTK_THEME_LIGHT="Arc"
export PREFERRED_GTK_THEME_DARK="Arc-Dark"

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s dwl >/dev/null 2>&1 && exec startw
