#!/bin/sh

background='#1a1a1a'
mainBlue='#268bd2'
fontsize=12
[ "$GDK_SCALE" -gt 1 ] && fontsize=20
font="Hack $fontsize"
horispacing=14

export BEMENU_OPTS="-n -i --tb "$background" --fn '"$font"' --tf "$mainBlue" --fb "$background" --nb "$background" --hb "$background" --hf "$mainBlue" -p '' --hp "$horispacing""
